-- AlterTable: add feijao fields to AgroDRERural
ALTER TABLE "AgroDRERural" ADD COLUMN IF NOT EXISTS "recFeijaoVolume" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "AgroDRERural" ADD COLUMN IF NOT EXISTS "recFeijaoPreco" DOUBLE PRECISION NOT NULL DEFAULT 0;
